_wandb:
    value:
        cli_version: 0.21.0
        e:
            53wv2603jo48olfeza9aaxvh35cb9y53:
                args:
                    - --manifest
                    - metadata/mof_manifest.csv
                    - --soap-dir
                    - outputs/soap_2d
                    - --soap-meta
                    - outputs/soap_2d/manifest.json
                    - --labels
                    - ../comb_id_labels.csv
                    - --output-dir
                    - outputs/set_transformer/contrastive
                    - --epochs
                    - "80"
                    - --batch-size
                    - "16"
                    - --atom-drop
                    - "0.3"
                    - --feature-drop
                    - "0.15"
                    - --latent-dim
                    - "510"
                codePath: soap_pipeline_clean/scripts/pretrain_contrastive.py
                codePathLocal: scripts/pretrain_contrastive.py
                cpu_count: 128
                cpu_count_logical: 128
                cudaVersion: "12.2"
                disk:
                    /:
                        total: "10737418240"
                        used: "5459378176"
                email: mmm9886@nyu.edu
                executable: /home/mmm9886/.conda/envs/soap_analysis/bin/python
                git:
                    commit: 87dfd9bb9cba77e5b97094b89782eeb873452501
                    remote: git@github.com:Mashrafi27/SOAP.git
                gpu: NVIDIA A100-PCIE-40GB
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Ampere
                      cudaCores: 6912
                      memoryTotal: "42949672960"
                      name: NVIDIA A100-PCIE-40GB
                      uuid: GPU-eeae9fe9-fea7-51a9-63ae-4cb789e54c14
                host: cn008
                memory:
                    total: "539903250432"
                os: Linux-4.18.0-513.5.1.el8_9.x86_64-x86_64-with-glibc2.28
                program: /scratch/mmm9886/Chignolin_Trajectory/SOAP_research/soap_pipeline_clean/scripts/pretrain_contrastive.py
                python: CPython 3.9.23
                root: /scratch/mmm9886/Chignolin_Trajectory/SOAP_research/soap_pipeline_clean
                slurm:
                    cluster_name: hpc
                    conf: /opt/slurm/etc/slurm.conf
                    cpus_on_node: "8"
                    cpus_per_task: "8"
                    gtids: "0"
                    job_account: students
                    job_cpus_per_node: "8"
                    job_gid: "100"
                    job_gpus: "2"
                    job_id: "12852277"
                    job_name: st_contrast
                    job_nodelist: cn008
                    job_num_nodes: "1"
                    job_partition: nvidia
                    job_qos: nvidias
                    job_uid: "3621466"
                    job_user: mmm9886
                    jobid: "12852277"
                    localid: "0"
                    mem_per_node: "65536"
                    nnodes: "1"
                    node_aliases: (null)
                    nodeid: "0"
                    nodelist: cn008
                    prio_process: "0"
                    procid: "0"
                    submit_dir: /scratch/mmm9886/Chignolin_Trajectory/SOAP_research/soap_pipeline_clean
                    submit_host: login1.fast
                    task_pid: "544889"
                    tasks_per_node: "1"
                    topology_addr: cn-spine.leaf03.cn008
                    topology_addr_pattern: switch.switch.node
                    working_cluster: hpc:slurm:6816:9216:109
                startedAt: "2025-11-13T14:52:35.856173Z"
                writerId: 53wv2603jo48olfeza9aaxvh35cb9y53
        m: []
        python_version: 3.9.23
        t:
            "1":
                - 1
                - 5
                - 53
                - 105
            "2":
                - 1
                - 5
                - 53
                - 105
            "3":
                - 2
                - 13
                - 16
            "4": 3.9.23
            "5": 0.21.0
            "12": 0.21.0
            "13": linux-x86_64
atom_drop:
    value: 0.3
base_size:
    value: 3089
batch_size:
    value: 16
dim_hidden:
    value: 256
epochs:
    value: 80
feature_drop:
    value: 0.15
labels:
    value: ../comb_id_labels.csv
latent_dim:
    value: 510
lr:
    value: 0.001
manifest:
    value: metadata/mof_manifest.csv
new_count:
    value: 0
num_heads:
    value: 4
num_inds:
    value: 32
output_dir:
    value: outputs/set_transformer/contrastive
soap_dir:
    value: outputs/soap_2d
soap_meta:
    value: outputs/soap_2d/manifest.json
temperature:
    value: 0.1
weight_decay:
    value: 1e-05
